project:
  type: website
  output-dir: docs
website:
  title: "Cecil's Data Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Cecilsingh
      - icon: linkedin
        href: https://www.linkedin.com/in/cecil-singh/
format:
  html:
    theme: yeti
    css: styles.css



